name: Run tsc
on: pull_request

jobs:
    tsc:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v4 # このあたりでエラーが出るとバージョンを上げないといけない
              with:
                  node-version: "20" # 使用するNode.jsのバージョンを指定

            - name: Install dependencies
              run: npm install
              working-directory: ./frontend

            - name: Run TypeScript compiler
              run: npm run tsc # または、直接 tsc コマンドを実行する
              working-directory: ./frontend

            - name: Run Biome checks
              run: npx biome check
              working-directory: ./frontend
